name: dance_recorder
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^0.8.7+4
  video_player: ^2.5.1
  ffmpeg_kit_flutter_full_gpl:
    git:
      url: https://github.com/Sahad2701/ffmpeg_kit_flutter_full_gpl.git
      ref: flutter-upgrade/remove-v1-embedding
  path_provider: ^2.0.14 # For accessing temporary directories

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Register the assets folder containing your reference videos.
  assets:
    - assets/videos/
